services:
  - type: web
    name: it-inventory-backend
    runtime: python
    branch: main
    repo: https://github.com/William10083/it-inventory
    rootDir: backend
    buildCommand: pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
